[package]
name = "git-checkout-interactive-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.1"
git2 = "0.14"
inquire = "0.2.1"
structopt = "0.3"
