name: Github Release

on:
  push:
    tags:

      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    uses: ./.github/workflows/integration.yml
  release:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/git-checkout-interactive-rust
      - name: Publish Crate
        run: cargo publish --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
