name: Github Release

on:
  push:
    tags:

      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    uses: ./.github/workflows/integration.yml
  build-release:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Release
        uses: softprops/action-gh-release@v1